name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # 触发条件：推送版本标签，如 v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # 必须，用于 Trusted Publishing

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # 指定 Python 版本

      # 安装构建依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      # 构建包
      - name: Build package
        run: python -m build

      # 发布到 PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/  # 默认 PyPI 地址
